[package]
name = "sashstore"
version = "0.1.0"
authors = ["Gerd Zellweger <gzellweger@vmware.com>"]
edition = "2018"


[[bench]]
name = "hashbench"
harness = false

[dependencies]
log = "0.4"


[target.'cfg(target_os = "linux")'.dependencies]
num_cpus = "1.10"
hwloc = "0.5.0"
env_logger = "0.7.1"
clap = { version = "2", features = ["yaml"] }
core_affinity = { git = "https://github.com/nau/core_affinity_rs", branch = "patch-1" }
socket2 = { version = "0.3", features = ["reuseport"] }
nix = "0.17"
mio = "0.6"
jemallocator = "0.3.2"

[target.'cfg(target_os = "linux")'.dev-dependencies]
zipf = "6.0.1"
rand = { version = "0.7", features = ["small_rng"] }
index = { git = "https://github.com/gz/Index" }
indexmap = "1.3.2"
jemalloc-ctl = "0.3.3"

# Add debug symbols on the release build so that we can debug performance issues
[profile.release]
debug = true
incremental = false
lto = true
codegen-units = 1

[profile.bench]
debug = true